name: ww3_clock
description: World War 3 Clock - AI-powered global tension monitor
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0  # Alternative to http, better for complex APIs
  
  # State Management
  provider: ^6.1.1
  
  # UI & Charts
  fl_chart: ^0.66.0  # Beautiful charts
  gauge_indicator: ^0.4.3  # Gauge widget for threat level
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  
  # Utilities
  intl: ^0.19.0  # Date formatting
  shared_preferences: ^2.2.2  # Local storage
  cached_network_image: ^3.3.0  # Image caching
  url_launcher: ^6.2.2  # Open URLs
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add assets folder for images/icons
  assets:
    - assets/images/
    - assets/icons/