// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1CiGTINn3eJ6bvb-e2MA3xMgD3V9JVgc',
    appId: '1:192415628608:web:49789000103938a0344ea5',
    messagingSenderId: '192415628608',
    projectId: 'ww3-clock',
    authDomain: 'ww3-clock.firebaseapp.com',
    storageBucket: 'ww3-clock.firebasestorage.app',
    measurementId: 'G-ZEPVWGRLG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChAqSrk0ITaF28-iPApMD2lpwVtAUZFoU',
    appId: '1:192415628608:android:93ff54dc7d7f4945344ea5',
    messagingSenderId: '192415628608',
    projectId: 'ww3-clock',
    storageBucket: 'ww3-clock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe5HrnmpSisw2nkmQJutG7WaM8OTIumxw',
    appId: '1:192415628608:ios:cc03f06efe9b18e3344ea5',
    messagingSenderId: '192415628608',
    projectId: 'ww3-clock',
    storageBucket: 'ww3-clock.firebasestorage.app',
    iosBundleId: 'com.example.ww3Clock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe5HrnmpSisw2nkmQJutG7WaM8OTIumxw',
    appId: '1:192415628608:ios:cc03f06efe9b18e3344ea5',
    messagingSenderId: '192415628608',
    projectId: 'ww3-clock',
    storageBucket: 'ww3-clock.firebasestorage.app',
    iosBundleId: 'com.example.ww3Clock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1CiGTINn3eJ6bvb-e2MA3xMgD3V9JVgc',
    appId: '1:192415628608:web:568d11d3300d0db2344ea5',
    messagingSenderId: '192415628608',
    projectId: 'ww3-clock',
    authDomain: 'ww3-clock.firebaseapp.com',
    storageBucket: 'ww3-clock.firebasestorage.app',
    measurementId: 'G-HVKTKRBG0G',
  );
}
